//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoReservaciones.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReservacionesDBEntities : DbContext
    {
        public ReservacionesDBEntities()
            : base("name=ReservacionesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Habitacion> Habitacion { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Reservacion> Reservacion { get; set; }
    
        public virtual ObjectResult<spConsultarTodasReservaciones_Result> spConsultarTodasReservaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarTodasReservaciones_Result>("spConsultarTodasReservaciones");
        }
    
        public virtual ObjectResult<spConsultarReservacionesCliente_Result> spConsultarReservacionesCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarReservacionesCliente_Result>("spConsultarReservacionesCliente");
        }
    
        public virtual ObjectResult<spConsultarReservacionesEmpleado_Result> spConsultarReservacionesEmpleado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarReservacionesEmpleado_Result>("spConsultarReservacionesEmpleado");
        }
    
        public virtual ObjectResult<spConsultaUsuario_Result> spConsultaUsuario(string correo, string contrasena)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaUsuario_Result>("spConsultaUsuario", correoParameter, contrasenaParameter);
        }
    
        public virtual ObjectResult<spConsultarReservacionesClienteID_Result> spConsultarReservacionesClienteID(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarReservacionesClienteID_Result>("spConsultarReservacionesClienteID", idClienteParameter);
        }
    
        public virtual ObjectResult<spConsultarReservacionesEmpleadoExcluir_Result> spConsultarReservacionesEmpleadoExcluir(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarReservacionesEmpleadoExcluir_Result>("spConsultarReservacionesEmpleadoExcluir", idClienteParameter);
        }
    
        public virtual ObjectResult<spConsultaUsuarioFiltro_Result> spConsultaUsuarioFiltro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaUsuarioFiltro_Result>("spConsultaUsuarioFiltro");
        }
    
        public virtual ObjectResult<spConsultarReservacionesEmpleadoFiltrado_Result> spConsultarReservacionesEmpleadoFiltrado(Nullable<int> idCliente, Nullable<System.DateTime> fechaEntrada, Nullable<System.DateTime> fechaSalida)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            var fechaEntradaParameter = fechaEntrada.HasValue ?
                new ObjectParameter("fechaEntrada", fechaEntrada) :
                new ObjectParameter("fechaEntrada", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("fechaSalida", fechaSalida) :
                new ObjectParameter("fechaSalida", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarReservacionesEmpleadoFiltrado_Result>("spConsultarReservacionesEmpleadoFiltrado", idClienteParameter, fechaEntradaParameter, fechaSalidaParameter);
        }
    
        public virtual ObjectResult<spConsultarBitacoraID_Result> spConsultarBitacoraID(Nullable<int> idReservacion)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("idReservacion", idReservacion) :
                new ObjectParameter("idReservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarBitacoraID_Result>("spConsultarBitacoraID", idReservacionParameter);
        }
    
        public virtual ObjectResult<spConsultaHotelFiltro_Result> spConsultaHotelFiltro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaHotelFiltro_Result>("spConsultaHotelFiltro");
        }
    
        public virtual ObjectResult<spConsultarHabitacionDisponible_Result> spConsultarHabitacionDisponible(Nullable<int> capacidad, Nullable<int> idHotel)
        {
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("capacidad", capacidad) :
                new ObjectParameter("capacidad", typeof(int));
    
            var idHotelParameter = idHotel.HasValue ?
                new ObjectParameter("idHotel", idHotel) :
                new ObjectParameter("idHotel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarHabitacionDisponible_Result>("spConsultarHabitacionDisponible", capacidadParameter, idHotelParameter);
        }
    
        public virtual int spInsertarBitacora(Nullable<int> idReservacion, Nullable<int> idPersona, string accion, Nullable<System.DateTime> fecha)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("idReservacion", idReservacion) :
                new ObjectParameter("idReservacion", typeof(int));
    
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("idPersona", idPersona) :
                new ObjectParameter("idPersona", typeof(int));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarBitacora", idReservacionParameter, idPersonaParameter, accionParameter, fechaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spConsultarUltimaReservacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spConsultarUltimaReservacion");
        }
    
        public virtual int spCrearReservacion(Nullable<int> idPersona, Nullable<int> idHabitacion, Nullable<System.DateTime> fechaEntrada, Nullable<System.DateTime> fechaSalida, Nullable<int> numeroAdultos, Nullable<int> numeroNinhos, Nullable<System.DateTime> fechaCreacion)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("idPersona", idPersona) :
                new ObjectParameter("idPersona", typeof(int));
    
            var idHabitacionParameter = idHabitacion.HasValue ?
                new ObjectParameter("idHabitacion", idHabitacion) :
                new ObjectParameter("idHabitacion", typeof(int));
    
            var fechaEntradaParameter = fechaEntrada.HasValue ?
                new ObjectParameter("fechaEntrada", fechaEntrada) :
                new ObjectParameter("fechaEntrada", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("fechaSalida", fechaSalida) :
                new ObjectParameter("fechaSalida", typeof(System.DateTime));
    
            var numeroAdultosParameter = numeroAdultos.HasValue ?
                new ObjectParameter("numeroAdultos", numeroAdultos) :
                new ObjectParameter("numeroAdultos", typeof(int));
    
            var numeroNinhosParameter = numeroNinhos.HasValue ?
                new ObjectParameter("numeroNinhos", numeroNinhos) :
                new ObjectParameter("numeroNinhos", typeof(int));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("fechaCreacion", fechaCreacion) :
                new ObjectParameter("fechaCreacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCrearReservacion", idPersonaParameter, idHabitacionParameter, fechaEntradaParameter, fechaSalidaParameter, numeroAdultosParameter, numeroNinhosParameter, fechaCreacionParameter);
        }
    
        public virtual int spEditarReservacion(Nullable<int> idReservacion, Nullable<System.DateTime> fechaEntrada, Nullable<System.DateTime> fechaSalida, Nullable<int> numAdultos, Nullable<int> numNinhos, Nullable<System.DateTime> fechaModificacion)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("idReservacion", idReservacion) :
                new ObjectParameter("idReservacion", typeof(int));
    
            var fechaEntradaParameter = fechaEntrada.HasValue ?
                new ObjectParameter("fechaEntrada", fechaEntrada) :
                new ObjectParameter("fechaEntrada", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("fechaSalida", fechaSalida) :
                new ObjectParameter("fechaSalida", typeof(System.DateTime));
    
            var numAdultosParameter = numAdultos.HasValue ?
                new ObjectParameter("numAdultos", numAdultos) :
                new ObjectParameter("numAdultos", typeof(int));
    
            var numNinhosParameter = numNinhos.HasValue ?
                new ObjectParameter("numNinhos", numNinhos) :
                new ObjectParameter("numNinhos", typeof(int));
    
            var fechaModificacionParameter = fechaModificacion.HasValue ?
                new ObjectParameter("fechaModificacion", fechaModificacion) :
                new ObjectParameter("fechaModificacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditarReservacion", idReservacionParameter, fechaEntradaParameter, fechaSalidaParameter, numAdultosParameter, numNinhosParameter, fechaModificacionParameter);
        }
    
        public virtual ObjectResult<spConsultarReservacionID_Result> spConsultarReservacionID(Nullable<int> idReservacion)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("idReservacion", idReservacion) :
                new ObjectParameter("idReservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarReservacionID_Result>("spConsultarReservacionID", idReservacionParameter);
        }
    
        public virtual ObjectResult<spConsultarHabitacionDisponibleID_Result> spConsultarHabitacionDisponibleID(Nullable<int> capacidad, Nullable<int> idHabitacion)
        {
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("capacidad", capacidad) :
                new ObjectParameter("capacidad", typeof(int));
    
            var idHabitacionParameter = idHabitacion.HasValue ?
                new ObjectParameter("idHabitacion", idHabitacion) :
                new ObjectParameter("idHabitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarHabitacionDisponibleID_Result>("spConsultarHabitacionDisponibleID", capacidadParameter, idHabitacionParameter);
        }
    
        public virtual int spCancelarReservacion(Nullable<int> idReservacion, Nullable<System.DateTime> fechaModificacion)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("idReservacion", idReservacion) :
                new ObjectParameter("idReservacion", typeof(int));
    
            var fechaModificacionParameter = fechaModificacion.HasValue ?
                new ObjectParameter("fechaModificacion", fechaModificacion) :
                new ObjectParameter("fechaModificacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCancelarReservacion", idReservacionParameter, fechaModificacionParameter);
        }
    }
}
